-- Translate team names to English in matches table
update public.matches set home_team = case home_team
  when 'México' then 'Mexico'
  when 'Corea del Sur' then 'South Korea'
  when 'Sudáfrica' then 'South Africa'
  when 'República Checa' then 'Czech Republic'
  when 'Canadá' then 'Canada'
  when 'Suiza' then 'Switzerland'
  when 'Bosnia-Herzegovina' then 'Bosnia & Herzegovina'
  when 'Haití' then 'Haiti'
  when 'Escocia' then 'Scotland'
  when 'Estados Unidos' then 'USA'
  when 'Turquía' then 'Turkey'
  when 'Alemania' then 'Germany'
  when 'Curazao' then 'Curaçao'
  when 'Costa de Marfil' then 'Côte d''Ivoire'
  when 'Países Bajos' then 'Netherlands'
  when 'Japón' then 'Japan'
  when 'Suecia' then 'Sweden'
  when 'Túnez' then 'Tunisia'
  when 'Bélgica' then 'Belgium'
  when 'Irán' then 'Iran'
  when 'Egipto' then 'Egypt'
  when 'Nueva Zelanda' then 'New Zealand'
  when 'España' then 'Spain'
  when 'Arabia Saudita' then 'Saudi Arabia'
  when 'Cabo Verde' then 'Cape Verde'
  when 'Francia' then 'France'
  when 'Noruega' then 'Norway'
  when 'Irak' then 'Iraq'
  when 'Argelia' then 'Algeria'
  when 'Jordania' then 'Jordan'
  when 'Uzbekistán' then 'Uzbekistan'
  when 'Congo DR' then 'DR Congo'
  when 'Inglaterra' then 'England'
  when 'Croacia' then 'Croatia'
  when 'Panamá' then 'Panama'
  when 'Brasil' then 'Brazil'
  when 'Marruecos' then 'Morocco'
  else home_team
end;

update public.matches set away_team = case away_team
  when 'México' then 'Mexico'
  when 'Corea del Sur' then 'South Korea'
  when 'Sudáfrica' then 'South Africa'
  when 'República Checa' then 'Czech Republic'
  when 'Canadá' then 'Canada'
  when 'Suiza' then 'Switzerland'
  when 'Bosnia-Herzegovina' then 'Bosnia & Herzegovina'
  when 'Haití' then 'Haiti'
  when 'Escocia' then 'Scotland'
  when 'Estados Unidos' then 'USA'
  when 'Turquía' then 'Turkey'
  when 'Alemania' then 'Germany'
  when 'Curazao' then 'Curaçao'
  when 'Costa de Marfil' then 'Côte d''Ivoire'
  when 'Países Bajos' then 'Netherlands'
  when 'Japón' then 'Japan'
  when 'Suecia' then 'Sweden'
  when 'Túnez' then 'Tunisia'
  when 'Bélgica' then 'Belgium'
  when 'Irán' then 'Iran'
  when 'Egipto' then 'Egypt'
  when 'Nueva Zelanda' then 'New Zealand'
  when 'España' then 'Spain'
  when 'Arabia Saudita' then 'Saudi Arabia'
  when 'Cabo Verde' then 'Cape Verde'
  when 'Francia' then 'France'
  when 'Noruega' then 'Norway'
  when 'Irak' then 'Iraq'
  when 'Argelia' then 'Algeria'
  when 'Jordania' then 'Jordan'
  when 'Uzbekistán' then 'Uzbekistan'
  when 'Congo DR' then 'DR Congo'
  when 'Inglaterra' then 'England'
  when 'Croacia' then 'Croatia'
  when 'Panamá' then 'Panama'
  when 'Brasil' then 'Brazil'
  when 'Marruecos' then 'Morocco'
  else away_team
end;
